// Category context
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILED = 'GET_CATEGORIES_FAILED';

// Branch context
export const GET_BRANCHS = 'GET_BRANCHS';
export const GET_BRANCHS_SUCCESS = 'GET_BRANCHS_SUCCESS';
export const GET_BRANCHS_FAILED = 'GET_BRANCHS_FAILED';

export const GET_BRANCH = 'GET_BRANCH';
export const GET_BRANCH_SUCCESS = 'GET_BRANCH_SUCCESS';
export const GET_BRANCH_FAILED = 'GET_BRANCH_FAILED';

// Room context
export const GET_ROOMS = 'GET_ROOMS';
export const GET_ROOMS_SUCCESS = 'GET_ROOMS_SUCCESS';
export const GET_ROOMS_FAILED = 'GET_ROOMS_FAILED';

export const GET_ROOMS_BRANCH = 'GET_ROOMS_BRANCH';
export const GET_ROOMS_BRANCH_SUCCESS = 'GET_ROOMS_BRANCH_SUCCESS';
export const GET_ROOMS_BRANCH_FAILED = 'GET_ROOMS_BRANCH_FAILED';

export const GET_ROOM = 'GET_ROOM';
export const GET_ROOM_SUCCESS = 'GET_ROOM_SUCCESS';
export const GET_ROOM_FAILED = 'GET_ROOM_FAILED';

export const GET_FILTER_ROOMS = 'GET_FILTER_ROOMS';
export const GET_ALL_ROOMS = 'GET_ALL_ROOMS';

export const LOADING_FILERS = 'LOADING_FILTERS';


export const SET_CATEGORY_VIEW = 'SET_CATEGORY_VIEW';
export const SET_CATEGORY_VIEW_SUCCESS = 'SET_CATEGORY_VIEW_SUCCESS';
export const SET_CATEGORY_VIEW_FAILED = 'SET_CATEGORY_VIEW_FAILED';

export const CONTACT = 'CONTACT';
export const CONTACT_SUCCESS = 'CONTACT_SUCCESS';
export const CONTACT_FAILED = 'CONTACT_FAILED';